# Generated by Django 4.2.7 on 2025-12-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='会话ID')),
                ('status', models.SmallIntegerField(choices=[(0, '已关闭'), (1, '活跃')], default=1, help_text='状态: 0-closed, 1-active', verbose_name='状态')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('last_message_at', models.DateTimeField(verbose_name='最后消息时间')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'db_table': 'Conversation',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='PostEntity',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='发布信息ID')),
                ('post_type', models.SmallIntegerField(choices=[(1, '科研项目'), (2, '竞赛项目'), (3, '学生技能')], help_text='发布类型: 1-科研项目, 2-竞赛项目, 3-学生技能', verbose_name='发布类型')),
                ('create_time', models.DateTimeField(verbose_name='发布时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('favorite_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '发布实体',
                'verbose_name_plural': '发布实体',
                'db_table': 'Post_entity',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentEntity',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('student_name', models.CharField(max_length=255, verbose_name='学生姓名')),
                ('grade', models.SmallIntegerField(choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四')], help_text='年级: 1-大一, 2-大二, 3-大三, 4-大四', verbose_name='年级')),
            ],
            options={
                'verbose_name': '学生实体',
                'verbose_name_plural': '学生实体',
                'db_table': 'Student_entity',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签号')),
                ('name', models.CharField(max_length=255, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'Tag',
                'ordering': ['tag_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEntity',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='教工号')),
                ('teacher_name', models.CharField(max_length=255, verbose_name='教师姓名')),
                ('title', models.CharField(max_length=255, verbose_name='职称')),
            ],
            options={
                'verbose_name': '教师实体',
                'verbose_name_plural': '教师实体',
                'db_table': 'Teacher_entity',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('identity', models.SmallIntegerField(choices=[(0, '学生'), (1, '教师'), (2, '管理员')], help_text='身份: 0-学生, 1-教师, 2-管理员', verbose_name='身份')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='认证令牌')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStudentCooperation',
            fields=[
                ('cooperation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='合作关系ID')),
                ('role', models.BooleanField(verbose_name='角色')),
                ('status', models.SmallIntegerField(choices=[(0, 'invited'), (1, 'applied'), (2, 'pending'), (3, 'confirmed'), (4, 'rejected'), (5, 'finished')], help_text='状态: 0-发出邀请, 1-发出申请, 2-待双方确认, 3-已确认, 4-已拒绝, 5-已完成', verbose_name='状态')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.postentity', verbose_name='发布信息ID')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='api.studententity', verbose_name='学生ID')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacherentity', verbose_name='教师ID')),
            ],
            options={
                'verbose_name': '师生合作关系',
                'verbose_name_plural': '师生合作关系',
                'db_table': 'Teacher_student_cooperation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teacherentity',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', unique=True, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='studententity',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', unique=True, verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='消息ID')),
                ('content_type', models.SmallIntegerField(choices=[(0, '文字'), (1, '图片'), (2, '文件')], help_text='内容类型: 0-文字, 1-图片, 2-文件', verbose_name='内容类型')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('is_read', models.BooleanField(verbose_name='阅读状态数据')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, to='api.conversation', verbose_name='会话ID')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='发送者ID')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'Message',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to='api.user', verbose_name='发起者用户ID'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='api.user', verbose_name='接收者用户ID'),
        ),
        migrations.CreateModel(
            name='SkillInformation',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.postentity', verbose_name='发布信息ID')),
                ('major', models.CharField(max_length=255, verbose_name='专业')),
                ('skill', models.CharField(max_length=255, verbose_name='技能')),
                ('skill_degree', models.CharField(max_length=255, verbose_name='技能程度')),
                ('project_experience', models.CharField(max_length=255, verbose_name='项目经验')),
                ('experience_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='经验链接')),
                ('habit_tag', models.CharField(max_length=255, verbose_name='习惯标签')),
                ('spend_time', models.CharField(max_length=255, verbose_name='可投入时间')),
                ('expect_worktype', models.CharField(max_length=255, verbose_name='期望工作类型')),
                ('filter', models.CharField(max_length=255, verbose_name='筛选条件')),
                ('certification', models.CharField(blank=True, max_length=255, null=True, verbose_name='证书')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='api.studententity', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '学生技能发布',
                'verbose_name_plural': '学生技能发布',
                'db_table': 'Skill_information',
                'ordering': ['-post__create_time'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.postentity', verbose_name='发布信息ID')),
                ('research_name', models.CharField(max_length=255, verbose_name='科研项目名称')),
                ('research_direction', models.CharField(max_length=255, verbose_name='研究方向')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='技术栈')),
                ('recruit_quantity', models.IntegerField(verbose_name='招募数量')),
                ('starttime', models.DateTimeField(verbose_name='开始时间')),
                ('endtime', models.DateTimeField(verbose_name='结束时间')),
                ('outcome', models.CharField(max_length=255, verbose_name='预期成果')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('appendix', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacherentity', verbose_name='教师ID')),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'db_table': 'Research_project',
                'ordering': ['-post__create_time'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.postentity', verbose_name='发布信息ID')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='api.tag', verbose_name='标签ID')),
            ],
            options={
                'verbose_name': '发布信息标签',
                'verbose_name_plural': '发布信息标签',
                'db_table': 'Post_tag',
                'ordering': ['post', 'tag'],
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.postentity', verbose_name='发布信息ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'Like',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.postentity', verbose_name='发布信息ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'Favorite',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionProject',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.postentity', verbose_name='发布信息ID')),
                ('competition_type', models.CharField(max_length=255, verbose_name='竞赛类型')),
                ('competition_name', models.CharField(max_length=255, verbose_name='竞赛名称')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('team_require', models.CharField(max_length=255, verbose_name='团队要求')),
                ('guide_way', models.CharField(max_length=255, verbose_name='指导方式')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='奖励')),
                ('appendix', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teacherentity', verbose_name='教师ID')),
            ],
            options={
                'verbose_name': '竞赛项目',
                'verbose_name_plural': '竞赛项目',
                'db_table': 'Competition_project',
                'ordering': ['-post__create_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='api.postentity', verbose_name='发布信息ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'Comment',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
