# Generated by Django 4.2.7 on 2025-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="visibility",
            field=models.SmallIntegerField(
                choices=[(0, "公开"), (1, "仅教师可见"), (2, "仅学生可见")], default=0
            ),
        ),
    ]
