# Generated by Django 4.2.7 on 2025-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modify_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillinformation',
            name='expect_worktype',
            field=models.SmallIntegerField(choices=[(0, 'research'), (1, 'competition'), (2, 'innovation')], default=0, verbose_name='期望工作类型'),
        ),
        migrations.AlterField(
            model_name='skillinformation',
            name='filter',
            field=models.SmallIntegerField(choices=[(0, 'all'), (1, 'cross'), (2, 'local')], default=0, verbose_name='筛选条件'),
        ),
        migrations.AlterField(
            model_name='skillinformation',
            name='skill_degree',
            field=models.SmallIntegerField(choices=[(0, 'skillful'), (1, 'known')], default=0, verbose_name='技能程度'),
        ),
    ]
