# Generated by Django 4.2.7 on 2025-12-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_skillinformation_expect_worktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionproject',
            name='competition_type',
            field=models.SmallIntegerField(choices=[(0, 'IETP'), (1, 'AC'), (2, 'CC')], default=0, help_text='IETP-- 大创项目, AC-- 学科竞赛, CC-- 企业合作竞赛', verbose_name='竞赛类型'),
        ),
        migrations.AlterField(
            model_name='competitionproject',
            name='guide_way',
            field=models.SmallIntegerField(choices=[(0, 'online'), (1, 'offline')], default=0, verbose_name='指导方式'),
        ),
        migrations.AlterField(
            model_name='skillinformation',
            name='filter',
            field=models.SmallIntegerField(choices=[(0, 'all'), (1, 'cross'), (2, 'local')], default=0, help_text='all-- 全部, cross-- 可接受跨方向合作, local-- 优先本地项目', verbose_name='筛选条件'),
        ),
    ]
