# Generated by Django 4.2.7 on 2025-12-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_experience_file_to_experience_link'),
        ('api', '0003_user_deleted_at_user_is_active'),
    ]

    operations = [
    ]
