# Generated by Django 4.2.7 on 2025-12-31 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_deleted_at_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "direction_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="方向ID"
                    ),
                ),
                (
                    "direction_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="方向名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "方向",
                "verbose_name_plural": "方向",
                "db_table": "Direction",
                "ordering": ["direction_id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "skill_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="技能ID"
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="技能名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "技能",
                "verbose_name_plural": "技能",
                "db_table": "Skill",
                "ordering": ["skill_id"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "stack_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="技术栈ID"
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="技术栈名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "技术栈",
                "verbose_name_plural": "技术栈",
                "db_table": "Tech_stack",
                "ordering": ["stack_id"],
            },
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关联ID"
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(help_text="熟练度等级", verbose_name="熟练度"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postentity",
                        verbose_name="发布信息ID",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        db_column="skill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.skill",
                        verbose_name="技能ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生技能",
                "verbose_name_plural": "学生技能",
                "db_table": "Stu_skill",
                "ordering": ["id"],
                "unique_together": {("post", "skill")},
            },
        ),
        migrations.CreateModel(
            name="ResearchDirection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关联ID"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postentity",
                        verbose_name="发布信息ID",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        db_column="stack_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.techstack",
                        verbose_name="技术栈ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "科研方向",
                "verbose_name_plural": "科研方向",
                "db_table": "Research_direction",
                "ordering": ["id"],
                "unique_together": {("post", "stack")},
            },
        ),
        migrations.CreateModel(
            name="PostDirection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关联ID"
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        db_column="direction_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.direction",
                        verbose_name="方向ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postentity",
                        verbose_name="发布信息ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布方向",
                "verbose_name_plural": "发布方向",
                "db_table": "Post_direction",
                "ordering": ["id"],
                "unique_together": {("post", "direction")},
            },
        ),
    ]
