# Generated by Django 4.2.7 on 2025-12-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_competitionproject_competition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillinformation',
            name='expect_worktype',
            field=models.SmallIntegerField(choices=[(0, 'research'), (1, 'competition'), (2, 'innovation')], default=0, verbose_name='期望合作类型'),
        ),
    ]
