# Generated by Django 4.2.7 on 2025-12-31 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_direction_skill_techstack_studentskill_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResearchDirection",
            new_name="PostStack",
        ),
        migrations.AlterModelOptions(
            name="poststack",
            options={
                "ordering": ["id"],
                "verbose_name": "技术栈",
                "verbose_name_plural": "技术栈",
            },
        ),
        migrations.RemoveField(
            model_name="competitionproject",
            name="appendix",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="appendix",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="research_direction",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="tech_stack",
        ),
        migrations.RemoveField(
            model_name="skillinformation",
            name="certification",
        ),
        migrations.RemoveField(
            model_name="skillinformation",
            name="major",
        ),
        migrations.RemoveField(
            model_name="skillinformation",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="skillinformation",
            name="skill_degree",
        ),
        migrations.AlterModelTable(
            name="poststack",
            table="Post_stack",
        ),
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="附件ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=255, verbose_name="存储路径"),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="单位：字节", verbose_name="文件大小"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME类型"),
                ),
                (
                    "file_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "科研材料"),
                            (2, "大创或竞赛"),
                            (3, "个人证书简历"),
                            (4, "其他"),
                        ],
                        default=5,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "download_url",
                    models.URLField(max_length=500, verbose_name="下载URL"),
                ),
                (
                    "formatted_size",
                    models.CharField(
                        help_text="如: 1.5MB",
                        max_length=50,
                        verbose_name="格式化文件大小",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.postentity",
                        verbose_name="发布信息ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布附件",
                "verbose_name_plural": "发布附件",
                "db_table": "Post_attachment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post_id"], name="Post_attach_post_id_ee1b0a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Post_attach_created_b180bb_idx"
                    ),
                ],
            },
        ),
    ]
