# Generated by Django 4.2.7 on 2025-12-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_researchdirection_poststack_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postattachment",
            name="Post_attach_post_id_ee1b0a_idx",
        ),
        migrations.RemoveIndex(
            model_name="postattachment",
            name="Post_attach_created_b180bb_idx",
        ),
    ]
