# Generated by Django 4.2.7 on 2025-12-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_postattachment_post_attach_post_id_ee1b0a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="download_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="下载URL"
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="file_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "科研材料"),
                    (2, "大创或竞赛"),
                    (3, "个人证书简历"),
                    (4, "其他"),
                ],
                default=4,
                verbose_name="文件类型",
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="formatted_size",
            field=models.CharField(
                blank=True,
                help_text="如: 1.5MB",
                max_length=50,
                null=True,
                verbose_name="格式化文件大小",
            ),
        ),
    ]
