# Generated by Django 4.2.7 on 2026-01-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_postattachment_download_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skillinformation',
            name='experience_file',
        ),
        migrations.AddField(
            model_name='skillinformation',
            name='experience_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='经验链接'),
        ),
        migrations.AlterField(
            model_name='competitionproject',
            name='competition_type',
            field=models.SmallIntegerField(choices=[(0, 'IETP'), (1, 'AC'), (2, 'CC')], default=0, help_text='IETP-- 大创项目, AC-- 学科竞赛, CC-- 企业合作竞赛', verbose_name='竞赛类型'),
        ),
        migrations.AlterField(
            model_name='competitionproject',
            name='guide_way',
            field=models.SmallIntegerField(choices=[(0, 'online'), (1, 'offline')], default=0, verbose_name='指导方式'),
        ),
        migrations.AlterField(
            model_name='teacherstudentcooperation',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'pending'), (3, 'confirmed'), (4, 'rejected')], help_text='状态: 2-待双方确认, 3-已确认, 4-已拒绝', verbose_name='状态'),
        ),
    ]
