# Generated by Django 4.2.7 on 2025-12-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_unique_together_and_more'),
        ('api', '0007_alter_postattachment_download_url_and_more'),
    ]

    operations = [
    ]
