# Generated by Django 4.2.7 on 2025-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20251231_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillinformation',
            name='skill_degree',
        ),
        migrations.AlterField(
            model_name='skillinformation',
            name='expect_worktype',
            field=models.CharField(max_length=255, verbose_name='期望工作类型'),
        ),
        migrations.AlterField(
            model_name='skillinformation',
            name='filter',
            field=models.CharField(max_length=255, verbose_name='筛选条件'),
        ),
    ]
