# Generated by Django 4.2.7 on 2026-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_comment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_reply_enabled",
            field=models.BooleanField(default=False, verbose_name="自动回复已启用"),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_reply_message",
            field=models.TextField(blank=True, null=True, verbose_name="自动回复消息"),
        ),
    ]
