# Generated by Django 4.2.7 on 2025-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_skillinformation_skill_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillinformation',
            name='skill_degree',
        ),
    ]
