# Generated by Django 4.2.7 on 2026-01-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_auto_reply_enabled_user_auto_reply_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postattachment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                db_column="post_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="api.postentity",
                verbose_name="发布信息ID",
            ),
        ),
    ]
