# Generated by Django 4.2.7 on 2026-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_postattachment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstudentcooperation",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (2, "pending"),
                    (3, "confirmed"),
                    (4, "rejected"),
                    (5, "canceled"),
                ],
                help_text="状态: 2-待双方确认, 3-已确认, 4-已拒绝,5-已取消",
                verbose_name="状态",
            ),
        ),
    ]
