# Generated by Django 4.2.7 on 2026-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_teacherstudentcooperation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherentity",
            name="past_achievements",
            field=models.TextField(blank=True, null=True, verbose_name="往期指导成果"),
        ),
    ]
