# Generated by Django 4.2.7 on 2026-01-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_postentity_recruit_status"),
        ("api", "0012_teacherentity_past_achievements"),
    ]

    operations = []
